### ISSUE TITLE
大佬，我改良了你的EFI，clover升级到了5033，HDMI热插拔问题解决，开机后插HDMI也没事

### ISSUE THREAD

**Issue by howevergoy** [z0brk/NB5TK1_TJ1-Hackintosh#5]
大佬，我改良了你的EFI，clover升级到了5033，HDMI热插拔问题解决，开机后插HDMI也没事。
EFI的链接：https://github.com/yuedashen88/DC2_EFI
再次感谢大佬，么么哒

**Comment by z0brk** [comment]
感谢，smbios换成14,1确实可以解决hdmi
