### ISSUE TITLE
DD2,miniDP接口外接显示器无信号，hdmi正常

### ISSUE THREAD

**Issue by GSSYVGEG** [z0brk/NB5TK1_TJ1-Hackintosh#6]
dd2这台笔记本的dp口连接的应该是1050ti独立显卡。我试了10.13.6的nv web driver，无法驱动。目前装的是10.14.6，miniDP口无法使用。不知道有没有办法解决？dp口不能用导致外接的4k显示器无法跑在60hz

**Comment by z0brk** [comment]
独显已经屏蔽了
