### ISSUE TITLE
现在的版本是11.3.1，最近开始休眠唤醒后死机，甚至偶尔性出现，自动重启，或是自动断电，

### ISSUE THREAD

**Issue by pjiahao** [z0brk/NB5TK1_TJ1-Hackintosh#9]
现在的版本是11.3.1，最近开始休眠唤醒后死机，甚至偶尔性出现，自动重启，或是自动断电，

DD2  笔记本,9400款

**Comment by z0brk** [comment]
休眠唤醒后死机暂时未遇到，自动重启，或是自动断电为硬件缺陷，非Win都会出现这种情况。
下月初会更新OC 0.7.0
